name: Generate Matrix from Metadata Files

on:
  push:

jobs:
  build_and_prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Step
        run: |
          # Your build commands here
          # This should produce the dist directory with metadata.json files

      - id: create-matrix
        name: "Create metadata.json matrix"
        run: |
          if [ -d "json-files" ]; then

            # Initialize an empty JSON array
            MATRIX_JSON=$(jq -n '[]')
            # Flag to check if any files were processed
            FILES_PROCESSED=false
            
            # Loop through all metadata.json files in the specified directory
            for file in $(find json-files -name 'metadata.json'); do
              # Slurp the file content into the MATRIX_JSON array
              MATRIX_JSON=$(jq --argfile content $file '. += [$content]' <<< "$MATRIX_JSON")
              FILES_PROCESSED=true
            done
            
            # Only set matrix to output if processing has occured
            if [ "$FILES_PROCESSED" = true ]; then

              # Wrap the array in an 'include' object
              MATRIX_JSON=$(jq '{include: .}' <<< "$MATRIX_JSON")
            
              # Echo the final MATRIX_JSON into a file named 'matrix.json'
              echo "$MATRIX_JSON" > /tmp/matrix.json
            
              # Set the matrix JSON as an output variable using the $GITHUB_OUTPUT environment variable
              echo "matrix<<EOF" >> $GITHUB_OUTPUT
              cat /tmp/matrix.json >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT

              echo "🟢 Successfuly merged metadata.json:"
              cat /tmp/matrix.json
            else
              echo "🚨 metadata.json string is empty. No files were processed"
            fi
          else
            echo "🚨 Directory does not exist, skipping matrix creation."
          fi

  use_matrix:
    needs: build_and_prepare_matrix
    runs-on: ubuntu-latest
    if: ${{ needs.build_and_prepare_matrix.outputs.matrix }}
    strategy:
      matrix: ${{fromJson(needs.build_and_prepare_matrix.outputs.matrix)}}
    steps:
      - name: Use Matrix
        run: |
          echo "Using matrix context: ${{ matrix.dockerfile }}"
          echo "With name: ${{ matrix.dockerfile_working_directory }}"