name: Download Repo on Push

on:
  push:

#jobs:
#  prepare_matrix:
#    runs-on: ubuntu-latest
#    outputs:
#      matrix: ${{ steps.set-matrix.outputs.matrix }}
#    steps:
#      - run : echo "hello1" > /tmp/hello1.txt && echo "hello2" > /tmp/hello2.txt
#      - id: set-matrix
#        run: |
#          echo "::set-output name=matrix::{\"include\":[{\"context\":\"/tmp/hello1.txt\", \"name\":\"hello1\"},{\"context\":\"/tmp/hello2.txt\", \"name\":\"hello2\"}]}"
#
#  build_and_push:
#    needs: prepare_matrix
#    runs-on: ubuntu-latest
#    strategy:
#      matrix: ${{fromJson(needs.prepare_matrix.outputs.matrix)}}
#    steps:
#      - uses: actions/upload-artifact@4
#        with: 
#          name: ${{matrix.name}}
#          path: ${{matrix.context}}


      #-
      #  name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      #-
      #  name: Build and push
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: ${{ github.workspace }}/${{ matrix.context }}
      #    push: true
      #    tags: user/app:latest
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create a File
        run: |
          echo "Sample content for the artifact file" > sample.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sample-artifact
          path: sample.txt
