name: Generate Matrix from Metadata Files

on:
  push:

jobs:
  build_and_prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Step
        run: |
          # Your build commands here
          # This should produce the dist directory with metadata.json files

      - id: create-matrix
        run: |
          # Initialize an empty JSON array
          MATRIX_JSON=$(jq -n '[]')
          
          # Loop through all metadata.json files in the dist directory
          for file in $(find json-files -name 'metadata.json'); do
            # Slurp the file content into the MATRIX_JSON array
            MATRIX_JSON=$(jq --argfile content $file '. += [$content]' <<< "$MATRIX_JSON")
          done
          
          # Wrap the array in an 'include' object
          MATRIX_JSON=$(jq '{include: .}' <<< "$MATRIX_JSON")
          
          # Echo the final MATRIX_JSON into a file named 'matrix.json'
          echo "$MATRIX_JSON" > /tmp/matrix.json
          
          # Set to github env 
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          cat /tmp/matrix.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /tmp/matrix.json


  use_matrix:
    needs: build_and_prepare_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build_and_prepare_matrix.outputs.matrix)}}
    steps:
      - name: Use Matrix
        run: |
          echo "Using matrix context: ${{ matrix.dockerfile }}"
          echo "With name: ${{ matrix.dockerfile_working_directory }}"